server:
  port: 8111

spring:
  application:
    name: spring-cloud-producer

# Eureka 相关配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

# 开启熔断器
feign:
  hystrix:
    enabled: true 
